// prebuild.mjs — copy the latest parsed JSON and the generated .xlsx into
// web/public so the Next.js app can import them at build time and serve the
// xlsx as a downloadable file. Runs before `next dev` and `next build`.

import { readdirSync, copyFileSync, existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const dataDir = resolve(projectRoot, 'data');
const outputDir = resolve(projectRoot, 'output');
const publicDir = resolve(__dirname, 'public');
const libDir = resolve(__dirname, 'lib');

if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true });
if (!existsSync(libDir)) mkdirSync(libDir, { recursive: true });

// 1. Find the most recent parsed-MMDDYY.json
let latestJson = null;
let latestTag = null;
if (existsSync(dataDir)) {
  const jsons = readdirSync(dataDir).filter((f) => /^parsed-\d{6}\.json$/.test(f));
  if (jsons.length > 0) {
    // Sort by the YYMMDD-equivalent date suffix (MMDDYY → YYMMDD)
    jsons.sort((a, b) => {
      const ta = a.match(/parsed-(\d{2})(\d{2})(\d{2})\.json/);
      const tb = b.match(/parsed-(\d{2})(\d{2})(\d{2})\.json/);
      const ka = `${ta[3]}${ta[1]}${ta[2]}`;
      const kb = `${tb[3]}${tb[1]}${tb[2]}`;
      return kb.localeCompare(ka);
    });
    latestJson = resolve(dataDir, jsons[0]);
    latestTag = jsons[0].match(/parsed-(\d{6})\.json/)[1];
  }
}

if (!latestJson) {
  console.error('prebuild: no parsed JSON found in', dataDir);
  console.error('Run `node src/update.mjs <pdf>` first.');
  process.exit(1);
}

// 2. Write lib/data.js — a static import of the latest parsed JSON.
const data = JSON.parse(readFileSync(latestJson, 'utf8'));
writeFileSync(
  resolve(libDir, 'data.js'),
  `// Auto-generated by prebuild.mjs from ${latestJson}\nexport const dashboardData = ${JSON.stringify(data, null, 2)};\nexport const dataTag = ${JSON.stringify(latestTag)};\n`,
);
console.log(`prebuild: wrote lib/data.js from parsed-${latestTag}.json`);

// 3. Copy the latest .xlsx into public so the Download button works.
const xlsx = resolve(outputDir, 'Q1_2026_Earnings_Dashboard.xlsx');
if (existsSync(xlsx)) {
  copyFileSync(xlsx, resolve(publicDir, 'Q1_2026_Earnings_Dashboard.xlsx'));
  console.log('prebuild: copied Q1_2026_Earnings_Dashboard.xlsx → public/');
} else {
  console.warn('prebuild: WARN no xlsx at', xlsx);
}
